//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleShapeDrawerArchitectured.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleShapeDrawerArchitectured.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ↓↓↓  .
        /// </summary>
        internal static string ArrowDownLetter {
            get {
                return ResourceManager.GetString("ArrowDownLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ».
        /// </summary>
        internal static string ArrowLetter {
            get {
                return ResourceManager.GetString("ArrowLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ 
        ///
        ///         Amin Amiri Darban   ■ +98-912-9587177 ■ amin.amiri.darban@hotmail.com
        ///      https://www.aminamiridarban.ir ■ https://www.linkedin.com/in/aminamiridarban
        ///
        ///          ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓                                       .
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Please Select Between Below Color « 
        ///.
        /// </summary>
        internal static string AvailableColorsMessage {
            get {
                return ResourceManager.GetString("AvailableColorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Please Enter First Letter or Number Of Each Output Type You Want ::::.
        /// </summary>
        internal static string AvailableOutPutMessage {
            get {
                return ResourceManager.GetString("AvailableOutPutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Please Enter First Letter or Number Of Each Shape You Want To Draw ::::.
        /// </summary>
        internal static string AvailableShapesMessage {
            get {
                return ResourceManager.GetString("AvailableShapesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape should has border..!
        ///» Please Enter The Border Color.
        /// </summary>
        internal static string BorderMessage {
            get {
                return ResourceManager.GetString("BorderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Are You Sure ? (y/n).
        /// </summary>
        internal static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Hit ENTER to Continue or Just press Escape to exit the application..
        /// </summary>
        internal static string ContinueMessage {
            get {
                return ResourceManager.GetString("ContinueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  » Please Enter The Dimentions For This Shape ::::.
        /// </summary>
        internal static string DimensionsMessage {
            get {
                return ResourceManager.GetString("DimensionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Do you want to draw.
        /// </summary>
        internal static string DrawOrStore {
            get {
                return ResourceManager.GetString("DrawOrStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Entered.
        /// </summary>
        internal static string Entered {
            get {
                return ResourceManager.GetString("Entered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape should be fill with a color..!
        ///» Please Enter The Fill Color : .
        /// </summary>
        internal static string FillMessage {
            get {
                return ResourceManager.GetString("FillMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hope you enjoy the show case result and see you soon.  ; )
        ///Bye for Now..!
        ///
        ///Just hit ESCAPE(Esc) to Exit or the application will terminated automatically after few seconds..
        /// </summary>
        internal static string GoodByeMessage {
            get {
                return ResourceManager.GetString("GoodByeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Please Press/Input a Key ::::.
        /// </summary>
        internal static string KeyMessage {
            get {
                return ResourceManager.GetString("KeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to needs a valid value in.
        /// </summary>
        internal static string NeedsValue {
            get {
                return ResourceManager.GetString("NeedsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Requested shape declarations are .
        /// </summary>
        internal static string OutPutMessage {
            get {
                return ResourceManager.GetString("OutPutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Pressed.
        /// </summary>
        internal static string Pressed {
            get {
                return ResourceManager.GetString("Pressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to »Please Enter The Number Of Shapes You Want It To Draw« .
        /// </summary>
        internal static string QuantityMessage {
            get {
                return ResourceManager.GetString("QuantityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius Of Circle.
        /// </summary>
        internal static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Of Rectangle.
        /// </summary>
        internal static string RecLength {
            get {
                return ResourceManager.GetString("RecLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width Of Rectangle.
        /// </summary>
        internal static string RecWidth {
            get {
                return ResourceManager.GetString("RecWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ―.
        /// </summary>
        internal static string SeparatorChar {
            get {
                return ResourceManager.GetString("SeparatorChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string ShapeCircle {
            get {
                return ResourceManager.GetString("ShapeCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string ShapeRectangle {
            get {
                return ResourceManager.GetString("ShapeRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string ShapeSquare {
            get {
                return ResourceManager.GetString("ShapeSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        internal static string ShapeTriangle {
            get {
                return ResourceManager.GetString("ShapeTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Of Side A For Triangle.
        /// </summary>
        internal static string SideABLength {
            get {
                return ResourceManager.GetString("SideABLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Of Side C For Triangle.
        /// </summary>
        internal static string SideACLength {
            get {
                return ResourceManager.GetString("SideACLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Of Side B For Triangle.
        /// </summary>
        internal static string SideBCLength {
            get {
                return ResourceManager.GetString("SideBCLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Of Square.
        /// </summary>
        internal static string SideLength {
            get {
                return ResourceManager.GetString("SideLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » So, Let&apos;s Start Drawing ....
        /// </summary>
        internal static string StartDrawingMessage {
            get {
                return ResourceManager.GetString("StartDrawingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is more a math problem.At point A you have the sides s1, s3 with opposing side s2.The cosine formula then gives
        ///        2*s1* s3*cos(alpha) = s1 ^ 2 + s3 ^ 2 - s2 ^ 2.
        ///        Now the cosine is the projection of the angle to the horizontal axis, so you should have
        ///        x = s3 * cos(alpha) = (s1 ^ 2 + s3 ^ 2 - s2 ^ 2) / (2 * s1)
        ///        and correspondingly
        ///        y = sqrt(s3 ^ 2 - x ^ 2).
        ///        For the test side lengths 3,4,5 this would give
        ///        x = (3 ^ 2 + (5 ^ 2 - 4 ^ 2)) / (2 * 3) = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriangleMathMessage {
            get {
                return ResourceManager.GetString("TriangleMathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s try again..! » .
        /// </summary>
        internal static string TryAgainMessage {
            get {
                return ResourceManager.GetString("TryAgainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to draw the triangle correctly, you must enter acceptable vertices.
        /// </summary>
        internal static string UnAcceptableVertices {
            get {
                return ResourceManager.GetString("UnAcceptableVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, But this shape is undrawable. Seems you forgot to bind some parameters..
        /// </summary>
        internal static string UnDrawableShape {
            get {
                return ResourceManager.GetString("UnDrawableShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Unexpected Error Raised..!
        ///Please Inform Developer to solve this issue. ; ).
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key you pressed on, is not a recognized as valid key for this step..
        /// </summary>
        internal static string UnKnownKey {
            get {
                return ResourceManager.GetString("UnKnownKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, There is no known output base on your entry..!.
        /// </summary>
        internal static string UnKnownOutPut {
            get {
                return ResourceManager.GetString("UnKnownOutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, There is no known shape base on your entry..!.
        /// </summary>
        internal static string UnKnownShape {
            get {
                return ResourceManager.GetString("UnKnownShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, But this shape is unstoreable. Seems you forgot to bind some parameters..
        /// </summary>
        internal static string UnStorableShape {
            get {
                return ResourceManager.GetString("UnStorableShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Seems you entered unvalid input value.
        /// </summary>
        internal static string UnValidInput {
            get {
                return ResourceManager.GetString("UnValidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » Please Input a Value ::::.
        /// </summary>
        internal static string ValueMessage {
            get {
                return ResourceManager.GetString("ValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertice.
        /// </summary>
        internal static string Vertice {
            get {
                return ResourceManager.GetString("Vertice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to » This is a simple application to humbly present my coding, knowledge and abilities through .Net technology.
        ///
        ///▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ █ ConsoleShapesApp  █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
        ///
        ///
        ///.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The X Side.
        /// </summary>
        internal static string XSide {
            get {
                return ResourceManager.GetString("XSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y Side.
        /// </summary>
        internal static string YSide {
            get {
                return ResourceManager.GetString("YSide", resourceCulture);
            }
        }
    }
}
